stima_dev/core/urls.py
from django.conf.urls import url
from . import views
from  django.contrib.auth.views import login
from rest_framework.authtoken import views as rest_framework_views
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_jwt.views import verify_jwt_token


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^home/', views.home, name='home'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^redefinirSenha/$', views.redefinirSenha, name='redefinirSenha'),
    url(r'^login/auth/$', obtain_jwt_token, name='get_auth_token'),
    url(r'^login/verify/$', verify_jwt_token, name='verify_auth_token'),
]

stima_dev/stima_dev/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import settings
from django.views.static import serve


urlpatterns = [
    url(r'^', include('core.urls', namespace="core")),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('core.urls', namespace='account')),

]

stima_dev/core/models.py
from django.db import models
from django.contrib.auth.models import User

class manager(models.Model):
    CPF = models.CharField(max_length=11)
    nome = models.CharField(max_length=200)
    usuario = models.OneToOneField(User)
    telefone = models.CharField(max_length=16)

    def __str__(self): # chave primaria que vai ser mostrada no banco de dados das assinaturas
        return self.usuario.username # pra mostrar o cpf do assinante ao inves de 'Assinante object'

    ### get_absolute_URl    ## Slug etc

#
# Token Authentication
# Creates new tokes for newly added users
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


# RUN THESE COMANDS IN PYTHON SHELL TO CREATE TOKENS FOR ALL USERS
# from django.contrib.auth.models import User
# from rest_framework.authtoken.models import Token
#
# users = User.objects.all()
# for user in users:
#     token, created = Token.objects.get_or_create(user=user)
#     print (user.username, token.key)

stima_dev/core/views.py
import random
import datetime

from django.shortcuts import render, get_object_or_404 #<============###################################### get_object_or_404(filtros)
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django import forms
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.utils.crypto import get_random_string


from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from django.contrib.auth.decorators import login_required  #@login_required

# View of redirecting to home page
@api_view(['GET'])
@permission_classes((IsAuthenticated, ))
def home(request):
    return render(request, 'home.html')

def user_login(request):
    #desativada = False
    errado = False
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/home/')
            #else:
            #   desativada = True
        else:
            errado = True
    return render(request, 'login.html', {'errado': errado})  #{'desativada': desativada, 'errado': errado})

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/home/')

#
#
#
#  Modificar Isso
def redefinirSenha(request):
    finalizado = False
    invalido = False
    if request.method == 'POST':
        form = RedefinirSenhaForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['emailForm']
            senhaNova = get_random_string(length=8)
            try:
                usuario = User.objects.get(email=email)
                send_mail('Redefinição de senha',
                          'Sua senha foi redefinida para: ' + senhaNova + '. Essa senha pode ser alterada a qualquer momento, para isso basta acessar o site e clicar em "Alterar Senha", através do menu "Minha Conta"',
                          'support@gameception.com', [email])
                usuario.set_password(senhaNova)
                usuario.save()
                finalizado = True
            except:
                invalido = True
    else:
        form = RedefinirSenhaForm()
    return render(request, 'home.html', {'form': form, 'finalizado': finalizado, 'invalido': invalido})

# Form
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

# Form Redefinir Senha
class RedefinirSenhaForm(forms.Form):
    emailForm = forms.EmailField(label='email', widget=forms.TextInput(attrs={'placeholder': 'E-mail'}))
    def __init__(self, *args, **kwargs):
        super(RedefinirSenhaForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


stima_dev/core/templates/base.html

{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stima Home</title>
</head>

<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      {% load static %}<img src="{% static 'images/Stima3.png' %}" height="60" width="125" />
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Link 1 </a></li>
        <li><a href="#">Link 2 </a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
          <b>Welcome {{ user.username }} !!!</b>
          <li><a href="{% url 'account:logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'account:login' %}">Login</a></li>
        {% endif %}

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% block navbar %}{% endblock%}
</body>
</html>

stima_dev/core/templates/home.html
{% extends "base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stima Home</title>
</head>

{% block navbar %}

<b>AHA!!!!!</b>
<b>AHA!!!!!</b>
<b>AHA!!!!!</b>
<b>AHA!!!!!</b>
<b>AHA!!!!!</b>
<b>AHA!!!!!</b>
<b>AHA!!!!!</b>
<b>AHA!!!!!</b>

{% endblock %}

stima_dev/core/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block navbar %}

        <link href="http://getbootstrap.com/examples/signin/signin.css" rel="stylesheet">

        <form class="form-signin" role="form" method="post" action=".">
            {% csrf_token %}

            <h2 class="form-signin-heading">Insira suas informações de Login</h2>
            <input class="form-control" placeholder="Nome de Usuário" id="id_username" maxlength="254" name="username" type="text" required autofocus=""/>
            <input type="password" class="form-control" placeholder="Senha" id="id_password" name="password"  required />
            {% if errado %}
                <strong>O nome de usuário ou senha está incorreto.</strong><br><br>
            {% endif %}
            Esqueceu sua senha? (Função Indisponível) <a href="{% url 'account:redefinirSenha' %}">Clique aqui.</a><br><br>
            <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit" >Sign in</button>
        </form>

{% endblock %}